title: Ramsey King Data Science Portfolio
description: Here is a collection of my data science projects.  They are born from academia, curiosity, and the pursuit of continuous learning.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
